const PDFDocument = require('pdfkit');
const db = require('../config/db');

const generatePatientPDF = async (req, res) => {
  const { patientId } = req.params;
  try {
    const [patients] = await db.query('SELECT * FROM Patients WHERE patient_id = ?', [patientId]);
    if (patients.length === 0) return res.status(404).json({ success: false, message: 'Patient not found' });
    const patient = patients[0];

    const [treatments] = await db.query(`
      SELECT t.*, d.disease_name, u.name as doctor_name
      FROM Treatments t
      JOIN Diseases d ON t.disease_id = d.disease_id
      JOIN Users u ON t.doctor_id = u.user_id
      WHERE t.patient_id = ?
    `, [patientId]);

    const [followups] = await db.query(`
      SELECT f.* FROM Followups f
      JOIN Treatments t ON f.treatment_id = t.treatment_id
      WHERE t.patient_id = ? ORDER BY f.followup_date DESC LIMIT 20
    `, [patientId]);

    const [timeline] = await db.query(
      'SELECT * FROM Timeline_Events WHERE patient_id = ? ORDER BY event_date DESC LIMIT 15', [patientId]
    );

    const doc = new PDFDocument({ margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=patient_${patient.patient_code}.pdf`);
    doc.pipe(res);

    // Header
    doc.fillColor('#4a7c59').fontSize(24).font('Helvetica-Bold').text('AYUSHI', { align: 'center' });
    doc.fillColor('#666').fontSize(12).font('Helvetica').text('Ayurvedic Patient Data Management System', { align: 'center' });
    doc.moveDown(0.5);
    doc.strokeColor('#4a7c59').lineWidth(2).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(1);

    // Patient Details
    doc.fillColor('#4a7c59').fontSize(16).font('Helvetica-Bold').text('PATIENT REPORT');
    doc.moveDown(0.5);
    doc.fillColor('#333').fontSize(11).font('Helvetica');
    doc.text(`Patient Code: ${patient.patient_code}`);
    doc.text(`Name: ${patient.name}`);
    doc.text(`Age: ${patient.age} | Gender: ${patient.gender}`);
    doc.text(`Phone: ${patient.phone || 'N/A'}`);
    doc.text(`Address: ${patient.address || 'N/A'}`);
    doc.text(`Occupation: ${patient.occupation || 'N/A'}`);
    doc.text(`Registration Date: ${patient.registration_date}`);
    doc.moveDown(1);

    // Treatments
    doc.fillColor('#4a7c59').fontSize(14).font('Helvetica-Bold').text('TREATMENT HISTORY');
    doc.moveDown(0.5);
    treatments.forEach((t, i) => {
      doc.fillColor('#333').fontSize(10).font('Helvetica-Bold').text(`${i + 1}. ${t.disease_name}`);
      doc.font('Helvetica').text(`   Doctor: ${t.doctor_name} | Status: ${t.status} | Improvement: ${t.improvement_percentage}%`);
      doc.text(`   Period: ${t.start_date} to ${t.end_date || 'Ongoing'}`);
      if (t.current_notes) doc.text(`   Notes: ${t.current_notes}`);
      doc.moveDown(0.3);
    });
    doc.moveDown(0.5);

    // Follow-ups
    if (followups.length > 0) {
      doc.fillColor('#4a7c59').fontSize(14).font('Helvetica-Bold').text('RECENT FOLLOW-UPS');
      doc.moveDown(0.5);
      followups.slice(0, 10).forEach(f => {
        doc.fillColor('#333').fontSize(10).font('Helvetica');
        doc.text(`• ${f.followup_date}: ${f.symptoms || 'No symptoms reported'} - ${f.improvement_percentage}% improvement`);
        if (f.notes) doc.text(`  Notes: ${f.notes}`, { indent: 10 });
        doc.moveDown(0.2);
      });
      doc.moveDown(0.5);
    }

    // Timeline
    doc.fillColor('#4a7c59').fontSize(14).font('Helvetica-Bold').text('PATIENT TIMELINE');
    doc.moveDown(0.5);
    timeline.forEach(e => {
      doc.fillColor('#333').fontSize(10).font('Helvetica');
      doc.text(`• ${new Date(e.event_date).toLocaleDateString()}: ${e.event_title}`);
      doc.moveDown(0.2);
    });

    // Footer
    doc.moveDown(2);
    doc.strokeColor('#ddd').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);
    doc.fillColor('#888').fontSize(9).text(`Generated by AYUSHI on ${new Date().toLocaleString()}`, { align: 'center' });
    doc.text('⚠️ This report is for clinical documentation purposes only.', { align: 'center' });

    doc.end();
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

const generateClinicReport = async (req, res) => {
  try {
    const [stats] = await db.query(`
      SELECT COUNT(DISTINCT p.patient_id) as total_patients,
             SUM(CASE WHEN t.status='Cured' THEN 1 ELSE 0 END) as cured,
             SUM(CASE WHEN t.status='Ongoing' THEN 1 ELSE 0 END) as active,
             SUM(CASE WHEN t.status='Left Treatment' THEN 1 ELSE 0 END) as dropout,
             ROUND(SUM(CASE WHEN t.status='Cured' THEN 1 ELSE 0 END)*100.0/NULLIF(COUNT(t.treatment_id),0),1) as cure_rate
      FROM Patients p LEFT JOIN Treatments t ON p.patient_id = t.patient_id WHERE p.is_active=1
    `);
    const [doctors] = await db.query(`SELECT COUNT(*) as count FROM Users WHERE role='doctor' AND is_active=1`);

    const doc = new PDFDocument({ margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename=clinic_report.pdf');
    doc.pipe(res);

    doc.fillColor('#4a7c59').fontSize(28).font('Helvetica-Bold').text('AYUSHI', { align: 'center' });
    doc.fillColor('#666').fontSize(14).font('Helvetica').text('Clinic Performance Report', { align: 'center' });
    doc.fontSize(11).text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
    doc.moveDown(1);
    doc.strokeColor('#4a7c59').lineWidth(2).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(1);

    doc.fillColor('#4a7c59').fontSize(16).font('Helvetica-Bold').text('CLINIC STATISTICS');
    doc.moveDown(0.5);
    const s = stats[0];
    const items = [
      ['Total Patients', s.total_patients],
      ['Active Patients', s.active],
      ['Cured Patients', s.cured],
      ['Dropout Patients', s.dropout],
      ['Overall Cure Rate', `${s.cure_rate}%`],
      ['Active Doctors', doctors[0].count],
    ];
    items.forEach(([label, value]) => {
      doc.fillColor('#333').fontSize(12).font('Helvetica');
      doc.text(`${label}: `, { continued: true }).font('Helvetica-Bold').text(String(value));
    });

    doc.end();
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

module.exports = { generatePatientPDF, generateClinicReport };
